version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: laboratorio_mcp_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mcp_password
      POSTGRES_DB: laboratorio_mcp
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
